apiVersion: v1
kind: Secret
metadata:
  name: {{ include "svc-notifications.fullname" . }}-secret
  labels:
    {{- include "svc-notifications.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.env.dbPassword }}"
