FROM nginx:alpine
WORKDIR /usr/share/nginx/html
<<<<<<<< HEAD:sanitech-mfe/infra/dockerfiles/shell/Dockerfile
COPY frontend/shell/ .
========
COPY frontend/shell/src/ .
>>>>>>>> 1.1.x:sanitech-mfe/infra/dockerfiles/shell.Dockerfile
EXPOSE 80
