FROM nginx:alpine
WORKDIR /usr/share/nginx/html
<<<<<<<< HEAD:sanitech-mfe/infra/dockerfiles/mfe-admin/Dockerfile
COPY frontend/mfe-admin/ .
========
COPY frontend/mfe-doctor/src/ .
>>>>>>>> 1.1.x:sanitech-mfe/infra/dockerfiles/mfe-doctor.Dockerfile
EXPOSE 80
