services:
  postgres:
    ports:
      - "5434:5432"
  kafka:
    ports:
      - "9092:9092"
      - "29092:29092"
  livekit:
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
