name: "\U0001F41B Bug Report"
description: Segnala un bug o un comportamento inatteso
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Grazie per la segnalazione! Compila i campi seguenti per aiutarci a risolvere il problema.

  - type: textarea
    id: description
    attributes:
      label: Descrizione del bug
      description: Descrivi chiaramente il problema riscontrato.
      placeholder: "Quando clicco su X succede Y invece di Z..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passi per riprodurre
      description: Elenca i passi necessari per riprodurre il bug.
      placeholder: |
        1. Vai a '...'
        2. Clicca su '...'
        3. Osserva l'errore
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento atteso
      description: Cosa ti aspettavi che succedesse?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area interessata
      options:
        - Frontend (Angular SPA)
        - svc-gateway
        - svc-directory
        - svc-scheduling
        - svc-admissions
        - svc-consents
        - svc-docs
        - svc-notifications
        - svc-audit
        - svc-televisit
        - svc-payments
        - svc-prescribing
        - Infrastruttura (Docker, Kafka, Keycloak, ecc.)
        - Altro
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Ambiente
      options:
        - Local
        - Staging
        - Produzione
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot / Log
      description: Aggiungi screenshot o log rilevanti (opzionale).
    validations:
      required: false
