replicaCount: 2

image:
  repository: sanitech/svc-notifications
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8087

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

env:
  springProfilesActive: prod

  # Database
  dbUrl: jdbc:postgresql://postgres:5432/sanitech_notifications
  dbUser: sanitech
  dbPassword: sanitech

  # OIDC
  oauth2IssuerUri: http://keycloak:8080/realms/sanitech

  # Kafka
  kafkaBootstrapServers: kafka:9092

  # SMTP
  mailHost: smtp
  mailPort: 25
  mailFrom: no-reply@sanitech.example

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
