spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

sanitech:
  livekit:
    url: ${LIVEKIT_URL}
    api-key: ${LIVEKIT_API_KEY}
    api-secret: ${LIVEKIT_API_SECRET}

# Logging di produzione (livello sobrio).
logging:
  level:
    root: INFO
