apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "svc-docs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "svc-docs.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "svc-docs.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "svc-docs.name" . }}
    spec:
      containers:
        - name: svc-docs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
          {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
