services:
  shell:
    build:
      context: ..
      dockerfile: shell/Dockerfile
    ports:
      - "4200:80"

  mfe-patient:
    build:
      context: ..
      dockerfile: mfe-patient/Dockerfile
    ports:
      - "4301:80"

  mfe-doctor:
    build:
      context: ..
      dockerfile: mfe-doctor/Dockerfile
    ports:
      - "4302:80"

  mfe-admin:
    build:
      context: ..
      dockerfile: mfe-admin/Dockerfile
    ports:
      - "4303:80"
