FROM grafana/grafana:11.2.0

# Embed provisioning (datasources, dashboards).
COPY grafana/provisioning /etc/grafana/provisioning

# Ensure permissions remain readable by grafana user.
RUN chown -R grafana:grafana /etc/grafana/provisioning
