FROM quay.io/keycloak/keycloak:26.0.7

# Copia il realm da importare all'avvio
COPY keycloak /opt/keycloak/data/import

# Default: avvio in dev mode e import del realm
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-port=8080", "--import-realm", "--hostname-strict=false"]
