FROM nginx:alpine
WORKDIR /usr/share/nginx/html
<<<<<<<< HEAD:sanitech-mfe/infra/dockerfiles/mfe-patient/Dockerfile
COPY frontend/mfe-patient/ .
========
COPY frontend/mfe-patient/src/ .
>>>>>>>> 1.1.x:sanitech-mfe/infra/dockerfiles/mfe-patient.Dockerfile
EXPOSE 80
