services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sanitech_scheduling
      POSTGRES_USER: sanitech
      POSTGRES_PASSWORD: sanitech
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanitech -d sanitech_scheduling"]
      interval: 5s
      timeout: 5s
      retries: 20

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.7
    depends_on: [zookeeper]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  svc-scheduling:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/sanitech_scheduling
      DB_USER: sanitech
      DB_PASSWORD: sanitech
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # In locale puoi puntare all'issuer reale di Keycloak.
      # OAUTH2_ISSUER_URI: http://localhost:8081/realms/sanitech
      OAUTH2_ISSUER_URI: http://host.docker.internal:8081/realms/sanitech
    ports:
      - "8083:8083"
