name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & test
        run: ./mvnw -q test

      - name: Package
        run: ./mvnw -q -DskipTests package

      - name: Helm lint
        run: helm lint helm/svc-admissions
