# =========================
# Profile: local
# =========================
# Configurazioni specifiche per il profilo "local".
spring:
  jpa:
    properties:
      hibernate:
        # Abilita il logging delle query SQL.
        show_sql: true
