# =========================
# Profile: staging
# =========================
# Configurazioni specifiche per il profilo "staging".
spring:
  jpa:
    properties:
      hibernate:
        # Disabilita il logging delle query SQL.
        show_sql: false
