services:
  keycloak:
    ports:
      - "8081:8080"

  kafka:
    ports:
      - "29092:29092"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  mailhog:
    ports:
      - "8025:8025"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  svc-gateway:
    ports:
      - "8080:8080"

  svc-directory:
    ports:
      - "8082:8082"

  svc-scheduling:
    ports:
      - "8083:8083"

  svc-admissions:
    ports:
      - "8084:8084"

  svc-consents:
    ports:
      - "8085:8085"

  svc-docs:
    ports:
      - "8086:8086"

  svc-notifications:
    ports:
      - "8087:8087"

  svc-audit:
    ports:
      - "8088:8088"

  svc-televisit:
    ports:
      - "8089:8089"

  svc-payments:
    ports:
      - "8090:8090"

  svc-prescribing:
    ports:
      - "8091:8091"
