version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sanitech_admissions
      POSTGRES_USER: sanitech
      POSTGRES_PASSWORD: sanitech
    ports:
      # Espone Postgres localmente per test manuali
      - "5435:5432"

  redpanda:
    image: redpandadata/redpanda:v24.2.5
    command: >
      redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M
      --node-id 0 --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      # Kafka API
      - "9092:9092"
