FROM nginx:alpine
WORKDIR /usr/share/nginx/html
<<<<<<<< HEAD:sanitech-mfe/infra/dockerfiles/mfe-doctor/Dockerfile
COPY frontend/mfe-doctor/ .
========
COPY frontend/mfe-admin/src/ .
>>>>>>>> 1.1.x:sanitech-mfe/infra/dockerfiles/mfe-admin.Dockerfile
EXPOSE 80
